languageCode = 'en-us'

baseURL = "https://www.thewine.quest"

# The name of this wonderful theme ;-).
theme = "ananke"

# The browser tab name
title = "The Wine Quest"

[caches]
  [caches.images]
    dir = ':cacheDir/images'